var tabledata = [
	{
		"film_id": 1,
		"title": "ACADEMY DINOSAUR",
		"description": "A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 86,
		"replacement_cost": "20.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'academi':1 'battl':15 'canadian':20 'dinosaur':2 'drama':5 'epic':4 'feminist':8 'mad':11 'must':14 'rocki':21 'scientist':12 'teacher':17"
	},
	{
		"film_id": 2,
		"title": "ACE GOLDFINGER",
		"description": "A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "4.99",
		"length": 48,
		"replacement_cost": "12.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'ace':1 'administr':9 'ancient':19 'astound':4 'car':17 'china':20 'databas':8 'epistl':5 'explor':12 'find':15 'goldfing':2 'must':14"
	},
	{
		"film_id": 3,
		"title": "ADAPTATION HOLES",
		"description": "A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "2.99",
		"length": 50,
		"replacement_cost": "18.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'adapt':1 'astound':4 'baloon':19 'car':11 'factori':20 'hole':2 'lumberjack':8,16 'must':13 'reflect':5 'sink':14"
	},
	{
		"film_id": 4,
		"title": "AFFAIR PREJUDICE",
		"description": "A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 117,
		"replacement_cost": "26.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'affair':1 'chase':14 'documentari':5 'fanci':4 'frisbe':8 'lumberjack':11 'monkey':16 'must':13 'prejudic':2 'shark':19 'tank':20"
	},
	{
		"film_id": 5,
		"title": "AFRICAN EGG",
		"description": "A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 130,
		"replacement_cost": "22.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\"]",
		"fulltext": "'african':1 'chef':11 'dentist':14 'documentari':7 'egg':2 'fast':5 'fast-pac':4 'forens':19 'gulf':23 'mexico':25 'must':16 'pace':6 'pastri':10 'psychologist':20 'pursu':17"
	},
	{
		"film_id": 6,
		"title": "AGENT TRUMAN",
		"description": "A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "2.99",
		"length": 169,
		"replacement_cost": "17.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\"]",
		"fulltext": "'agent':1 'ancient':19 'boy':11 'china':20 'escap':14 'intrepid':4 'must':13 'panorama':5 'robot':8 'sumo':16 'truman':2 'wrestler':17"
	},
	{
		"film_id": 7,
		"title": "AIRPLANE SIERRA",
		"description": "A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "4.99",
		"length": 62,
		"replacement_cost": "28.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'airplan':1 'boat':20 'butler':11,16 'discov':14 'hunter':8 'jet':19 'must':13 'saga':5 'sierra':2 'touch':4"
	},
	{
		"film_id": 8,
		"title": "AIRPORT POLLOCK",
		"description": "A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "4.99",
		"length": 54,
		"replacement_cost": "15.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'airport':1 'ancient':18 'confront':14 'epic':4 'girl':11 'india':19 'monkey':16 'moos':8 'must':13 'pollock':2 'tale':5"
	},
	{
		"film_id": 9,
		"title": "ALABAMA DEVIL",
		"description": "A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "2.99",
		"length": 114,
		"replacement_cost": "21.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'administr':9 'alabama':1 'boat':23 'databas':8 'devil':2 'jet':22 'mad':12,18 'must':15 'outgun':16 'panorama':5 'scientist':13,19 'thought':4"
	},
	{
		"film_id": 10,
		"title": "ALADDIN CALENDAR",
		"description": "A Action-Packed Tale of a Man And a Lumberjack who must Reach a Feminist in Ancient China",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "4.99",
		"length": 63,
		"replacement_cost": "24.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'action':5 'action-pack':4 'aladdin':1 'ancient':20 'calendar':2 'china':21 'feminist':18 'lumberjack':13 'man':10 'must':15 'pack':6 'reach':16 'tale':7"
	},
	{
		"film_id": 11,
		"title": "ALAMO VIDEOTAPE",
		"description": "A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 126,
		"replacement_cost": "16.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'alamo':1 'bore':4 'butler':8 'cat':11 'chef':17 'convent':21 'epistl':5 'fight':14 'must':13 'mysql':20 'pastri':16 'videotap':2"
	},
	{
		"film_id": 12,
		"title": "ALASKA PHANTOM",
		"description": "A Fanciful Saga of a Hunter And a Pastry Chef who must Vanquish a Boy in Australia",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 136,
		"replacement_cost": "22.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'alaska':1 'australia':19 'boy':17 'chef':12 'fanci':4 'hunter':8 'must':14 'pastri':11 'phantom':2 'saga':5 'vanquish':15"
	},
	{
		"film_id": 13,
		"title": "ALI FOREVER",
		"description": "A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "4.99",
		"length": 150,
		"replacement_cost": "21.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'action':5 'action-pack':4 'ali':1 'battl':16 'canadian':21 'crocodil':13 'dentist':10 'drama':7 'feminist':18 'forev':2 'must':15 'pack':6 'rocki':22"
	},
	{
		"film_id": 14,
		"title": "ALICE FANTASIA",
		"description": "A Emotional Drama of a A Shark And a Database Administrator who must Vanquish a Pioneer in Soviet Georgia",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 94,
		"replacement_cost": "23.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'administr':13 'alic':1 'databas':12 'drama':5 'emot':4 'fantasia':2 'georgia':21 'must':15 'pioneer':18 'shark':9 'soviet':20 'vanquish':16"
	},
	{
		"film_id": 15,
		"title": "ALIEN CENTER",
		"description": "A Brilliant Drama of a Cat And a Mad Scientist who must Battle a Feminist in A MySQL Convention",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 46,
		"replacement_cost": "10.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'alien':1 'battl':15 'brilliant':4 'cat':8 'center':2 'convent':21 'drama':5 'feminist':17 'mad':11 'must':14 'mysql':20 'scientist':12"
	},
	{
		"film_id": 16,
		"title": "ALLEY EVOLUTION",
		"description": "A Fast-Paced Drama of a Robot And a Composer who must Battle a Astronaut in New Orleans",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 180,
		"replacement_cost": "23.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'alley':1 'astronaut':18 'battl':16 'compos':13 'drama':7 'evolut':2 'fast':5 'fast-pac':4 'must':15 'new':20 'orlean':21 'pace':6 'robot':10"
	},
	{
		"film_id": 17,
		"title": "ALONE TRIP",
		"description": "A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "0.99",
		"length": 82,
		"replacement_cost": "14.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':22 'alon':1 'boat':19 'charact':7 'compos':11 'dog':14 'fast':5 'fast-pac':4 'fun':23 'hous':24 'must':16 'outgun':17 'pace':6 'studi':8 'trip':2"
	},
	{
		"film_id": 18,
		"title": "ALTER VICTORY",
		"description": "A Thoughtful Drama of a Composer And a Feminist who must Meet a Secret Agent in The Canadian Rockies",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 57,
		"replacement_cost": "27.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'agent':17 'alter':1 'canadian':20 'compos':8 'drama':5 'feminist':11 'meet':14 'must':13 'rocki':21 'secret':16 'thought':4 'victori':2"
	},
	{
		"film_id": 19,
		"title": "AMADEUS HOLY",
		"description": "A Emotional Display of a Pioneer And a Technical Writer who must Battle a Man in A Baloon",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 113,
		"replacement_cost": "20.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'amadeus':1 'baloon':20 'battl':15 'display':5 'emot':4 'holi':2 'man':17 'must':14 'pioneer':8 'technic':11 'writer':12"
	},
	{
		"film_id": 20,
		"title": "AMELIE HELLFIGHTERS",
		"description": "A Boring Drama of a Woman And a Squirrel who must Conquer a Student in A Baloon",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "4.99",
		"length": 79,
		"replacement_cost": "23.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'ameli':1 'baloon':19 'bore':4 'conquer':14 'drama':5 'hellfight':2 'must':13 'squirrel':11 'student':16 'woman':8"
	},
	{
		"film_id": 21,
		"title": "AMERICAN CIRCUS",
		"description": "A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "4.99",
		"length": 129,
		"replacement_cost": "17.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'administr':17 'american':1 'astronaut':11 'circus':2 'databas':16 'drama':5 'face':14 'girl':8 'insight':4 'must':13 'shark':20 'tank':21"
	},
	{
		"film_id": 22,
		"title": "AMISTAD MIDSUMMER",
		"description": "A Emotional Character Study of a Dentist And a Crocodile who must Meet a Sumo Wrestler in California",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 85,
		"replacement_cost": "10.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'amistad':1 'california':20 'charact':5 'crocodil':12 'dentist':9 'emot':4 'meet':15 'midsumm':2 'must':14 'studi':6 'sumo':17 'wrestler':18"
	},
	{
		"film_id": 23,
		"title": "ANACONDA CONFESSIONS",
		"description": "A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "0.99",
		"length": 92,
		"replacement_cost": "9.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'anaconda':1 'australia':18 'confess':2 'dentist':8,11 'display':5 'fight':14 'girl':16 'lacklustur':4 'must':13"
	},
	{
		"film_id": 24,
		"title": "ANALYZE HOOSIERS",
		"description": "A Thoughtful Display of a Explorer And a Pastry Chef who must Overcome a Feminist in The Sahara Desert",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 181,
		"replacement_cost": "19.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'analyz':1 'chef':12 'desert':21 'display':5 'explor':8 'feminist':17 'hoosier':2 'must':14 'overcom':15 'pastri':11 'sahara':20 'thought':4"
	},
	{
		"film_id": 25,
		"title": "ANGELS LIFE",
		"description": "A Thoughtful Display of a Woman And a Astronaut who must Battle a Robot in Berlin",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "2.99",
		"length": 74,
		"replacement_cost": "15.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'angel':1 'astronaut':11 'battl':14 'berlin':18 'display':5 'life':2 'must':13 'robot':16 'thought':4 'woman':8"
	},
	{
		"film_id": 26,
		"title": "ANNIE IDENTITY",
		"description": "A Amazing Panorama of a Pastry Chef And a Boat who must Escape a Woman in An Abandoned Amusement Park",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "0.99",
		"length": 86,
		"replacement_cost": "15.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'abandon':20 'amaz':4 'amus':21 'anni':1 'boat':12 'chef':9 'escap':15 'ident':2 'must':14 'panorama':5 'park':22 'pastri':8 'woman':17"
	},
	{
		"film_id": 27,
		"title": "ANONYMOUS HUMAN",
		"description": "A Amazing Reflection of a Database Administrator And a Astronaut who must Outrace a Database Administrator in A Shark Tank",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "0.99",
		"length": 179,
		"replacement_cost": "12.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'administr':9,18 'amaz':4 'anonym':1 'astronaut':12 'databas':8,17 'human':2 'must':14 'outrac':15 'reflect':5 'shark':21 'tank':22"
	},
	{
		"film_id": 28,
		"title": "ANTHEM LUKE",
		"description": "A Touching Panorama of a Waitress And a Woman who must Outrace a Dog in An Abandoned Amusement Park",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 91,
		"replacement_cost": "16.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':19 'amus':20 'anthem':1 'dog':16 'luke':2 'must':13 'outrac':14 'panorama':5 'park':21 'touch':4 'waitress':8 'woman':11"
	},
	{
		"film_id": 29,
		"title": "ANTITRUST TOMATOES",
		"description": "A Fateful Yarn of a Womanizer And a Feminist who must Succumb a Database Administrator in Ancient India",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 168,
		"replacement_cost": "11.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'administr':17 'ancient':19 'antitrust':1 'databas':16 'fate':4 'feminist':11 'india':20 'must':13 'succumb':14 'tomato':2 'woman':8 'yarn':5"
	},
	{
		"film_id": 30,
		"title": "ANYTHING SAVANNAH",
		"description": "A Epic Story of a Pastry Chef And a Woman who must Chase a Feminist in An Abandoned Fun House",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "2.99",
		"length": 82,
		"replacement_cost": "27.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':20 'anyth':1 'chase':15 'chef':9 'epic':4 'feminist':17 'fun':21 'hous':22 'must':14 'pastri':8 'savannah':2 'stori':5 'woman':12"
	},
	{
		"film_id": 31,
		"title": "APACHE DIVINE",
		"description": "A Awe-Inspiring Reflection of a Pastry Chef And a Teacher who must Overcome a Sumo Wrestler in A U-Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 92,
		"replacement_cost": "16.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'apach':1 'awe':5 'awe-inspir':4 'boat':25 'chef':11 'divin':2 'inspir':6 'must':16 'overcom':17 'pastri':10 'reflect':7 'sumo':19 'teacher':14 'u':24 'u-boat':23 'wrestler':20"
	},
	{
		"film_id": 32,
		"title": "APOCALYPSE FLAMINGOS",
		"description": "A Astounding Story of a Dog And a Squirrel who must Defeat a Woman in An Abandoned Amusement Park",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "4.99",
		"length": 119,
		"replacement_cost": "11.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'abandon':19 'amus':20 'apocalyps':1 'astound':4 'defeat':14 'dog':8 'flamingo':2 'must':13 'park':21 'squirrel':11 'stori':5 'woman':16"
	},
	{
		"film_id": 33,
		"title": "APOLLO TEEN",
		"description": "A Action-Packed Reflection of a Crocodile And a Explorer who must Find a Sumo Wrestler in An Abandoned Mine Shaft",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 153,
		"replacement_cost": "15.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':22 'action':5 'action-pack':4 'apollo':1 'crocodil':10 'explor':13 'find':16 'mine':23 'must':15 'pack':6 'reflect':7 'shaft':24 'sumo':18 'teen':2 'wrestler':19"
	},
	{
		"film_id": 34,
		"title": "ARABIA DOGMA",
		"description": "A Touching Epistle of a Madman And a Mad Cow who must Defeat a Student in Nigeria",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 62,
		"replacement_cost": "29.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'arabia':1 'cow':12 'defeat':15 'dogma':2 'epistl':5 'mad':11 'madman':8 'must':14 'nigeria':19 'student':17 'touch':4"
	},
	{
		"film_id": 35,
		"title": "ARACHNOPHOBIA ROLLERCOASTER",
		"description": "A Action-Packed Reflection of a Pastry Chef And a Composer who must Discover a Mad Scientist in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "2.99",
		"length": 147,
		"replacement_cost": "24.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'action':5 'action-pack':4 'arachnophobia':1 'chef':11 'compos':14 'discov':17 'first':23 'mad':19 'man':24 'must':16 'pack':6 'pastri':10 'reflect':7 'rollercoast':2 'scientist':20 'space':25 'station':26"
	},
	{
		"film_id": 36,
		"title": "ARGONAUTS TOWN",
		"description": "A Emotional Epistle of a Forensic Psychologist And a Butler who must Challenge a Waitress in An Abandoned Mine Shaft",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "0.99",
		"length": 127,
		"replacement_cost": "12.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'abandon':20 'argonaut':1 'butler':12 'challeng':15 'emot':4 'epistl':5 'forens':8 'mine':21 'must':14 'psychologist':9 'shaft':22 'town':2 'waitress':17"
	},
	{
		"film_id": 37,
		"title": "ARIZONA BANG",
		"description": "A Brilliant Panorama of a Mad Scientist And a Mad Cow who must Meet a Pioneer in A Monastery",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "2.99",
		"length": 121,
		"replacement_cost": "28.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'arizona':1 'bang':2 'brilliant':4 'cow':13 'mad':8,12 'meet':16 'monasteri':21 'must':15 'panorama':5 'pioneer':18 'scientist':9"
	},
	{
		"film_id": 38,
		"title": "ARK RIDGEMONT",
		"description": "A Beautiful Yarn of a Pioneer And a Monkey who must Pursue a Explorer in The Sahara Desert",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 68,
		"replacement_cost": "25.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'ark':1 'beauti':4 'desert':20 'explor':16 'monkey':11 'must':13 'pioneer':8 'pursu':14 'ridgemont':2 'sahara':19 'yarn':5"
	},
	{
		"film_id": 39,
		"title": "ARMAGEDDON LOST",
		"description": "A Fast-Paced Tale of a Boat And a Teacher who must Succumb a Composer in An Abandoned Mine Shaft",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "0.99",
		"length": 99,
		"replacement_cost": "10.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'abandon':21 'armageddon':1 'boat':10 'compos':18 'fast':5 'fast-pac':4 'lost':2 'mine':22 'must':15 'pace':6 'shaft':23 'succumb':16 'tale':7 'teacher':13"
	},
	{
		"film_id": 40,
		"title": "ARMY FLINTSTONES",
		"description": "A Boring Saga of a Database Administrator And a Womanizer who must Battle a Waitress in Nigeria",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "0.99",
		"length": 148,
		"replacement_cost": "22.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'administr':9 'armi':1 'battl':15 'bore':4 'databas':8 'flintston':2 'must':14 'nigeria':19 'saga':5 'waitress':17 'woman':12"
	},
	{
		"film_id": 41,
		"title": "ARSENIC INDEPENDENCE",
		"description": "A Fanciful Documentary of a Mad Cow And a Womanizer who must Find a Dentist in Berlin",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "0.99",
		"length": 137,
		"replacement_cost": "17.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'arsenic':1 'berlin':19 'cow':9 'dentist':17 'documentari':5 'fanci':4 'find':15 'independ':2 'mad':8 'must':14 'woman':12"
	},
	{
		"film_id": 42,
		"title": "ARTIST COLDBLOODED",
		"description": "A Stunning Reflection of a Robot And a Moose who must Challenge a Woman in California",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 170,
		"replacement_cost": "10.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'artist':1 'california':18 'challeng':14 'coldblood':2 'moos':11 'must':13 'reflect':5 'robot':8 'stun':4 'woman':16"
	},
	{
		"film_id": 43,
		"title": "ATLANTIS CAUSE",
		"description": "A Thrilling Yarn of a Feminist And a Hunter who must Fight a Technical Writer in A Shark Tank",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 170,
		"replacement_cost": "15.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Behind the Scenes\"]",
		"fulltext": "'atlanti':1 'caus':2 'feminist':8 'fight':14 'hunter':11 'must':13 'shark':20 'tank':21 'technic':16 'thrill':4 'writer':17 'yarn':5"
	},
	{
		"film_id": 44,
		"title": "ATTACKS HATE",
		"description": "A Fast-Paced Panorama of a Technical Writer And a Mad Scientist who must Find a Feminist in An Abandoned Mine Shaft",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 113,
		"replacement_cost": "21.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':23 'attack':1 'fast':5 'fast-pac':4 'feminist':20 'find':18 'hate':2 'mad':14 'mine':24 'must':17 'pace':6 'panorama':7 'scientist':15 'shaft':25 'technic':10 'writer':11"
	},
	{
		"film_id": 45,
		"title": "ATTRACTION NEWTON",
		"description": "A Astounding Panorama of a Composer And a Frisbee who must Reach a Husband in Ancient Japan",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 83,
		"replacement_cost": "14.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'ancient':18 'astound':4 'attract':1 'compos':8 'frisbe':11 'husband':16 'japan':19 'must':13 'newton':2 'panorama':5 'reach':14"
	},
	{
		"film_id": 46,
		"title": "AUTUMN CROW",
		"description": "A Beautiful Tale of a Dentist And a Mad Cow who must Battle a Moose in The Sahara Desert",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "4.99",
		"length": 108,
		"replacement_cost": "13.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'autumn':1 'battl':15 'beauti':4 'cow':12 'crow':2 'dentist':8 'desert':21 'mad':11 'moos':17 'must':14 'sahara':20 'tale':5"
	},
	{
		"film_id": 47,
		"title": "BABY HALL",
		"description": "A Boring Character Study of a A Shark And a Girl who must Outrace a Feminist in An Abandoned Mine Shaft",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 153,
		"replacement_cost": "23.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\"]",
		"fulltext": "'abandon':21 'babi':1 'bore':4 'charact':5 'feminist':18 'girl':13 'hall':2 'mine':22 'must':15 'outrac':16 'shaft':23 'shark':10 'studi':6"
	},
	{
		"film_id": 48,
		"title": "BACKLASH UNDEFEATED",
		"description": "A Stunning Character Study of a Mad Scientist And a Mad Cow who must Kill a Car in A Monastery",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "4.99",
		"length": 118,
		"replacement_cost": "24.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'backlash':1 'car':19 'charact':5 'cow':14 'kill':17 'mad':9,13 'monasteri':22 'must':16 'scientist':10 'studi':6 'stun':4 'undef':2"
	},
	{
		"film_id": 49,
		"title": "BADMAN DAWN",
		"description": "A Emotional Panorama of a Pioneer And a Composer who must Escape a Mad Scientist in A Jet Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 162,
		"replacement_cost": "22.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'badman':1 'boat':21 'compos':11 'dawn':2 'emot':4 'escap':14 'jet':20 'mad':16 'must':13 'panorama':5 'pioneer':8 'scientist':17"
	},
	{
		"film_id": 50,
		"title": "BAKED CLEOPATRA",
		"description": "A Stunning Drama of a Forensic Psychologist And a Husband who must Overcome a Waitress in A Monastery",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "2.99",
		"length": 182,
		"replacement_cost": "20.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'bake':1 'cleopatra':2 'drama':5 'forens':8 'husband':12 'monasteri':20 'must':14 'overcom':15 'psychologist':9 'stun':4 'waitress':17"
	},
	{
		"film_id": 51,
		"title": "BALLOON HOMEWARD",
		"description": "A Insightful Panorama of a Forensic Psychologist And a Mad Cow who must Build a Mad Scientist in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 75,
		"replacement_cost": "10.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\"]",
		"fulltext": "'balloon':1 'build':16 'cow':13 'first':22 'forens':8 'homeward':2 'insight':4 'mad':12,18 'man':23 'must':15 'panorama':5 'psychologist':9 'scientist':19 'space':24 'station':25"
	},
	{
		"film_id": 52,
		"title": "BALLROOM MOCKINGBIRD",
		"description": "A Thrilling Documentary of a Composer And a Monkey who must Find a Feminist in California",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 173,
		"replacement_cost": "29.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'ballroom':1 'california':18 'compos':8 'documentari':5 'feminist':16 'find':14 'mockingbird':2 'monkey':11 'must':13 'thrill':4"
	},
	{
		"film_id": 53,
		"title": "BANG KWAI",
		"description": "A Epic Drama of a Madman And a Cat who must Face a A Shark in An Abandoned Amusement Park",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 87,
		"replacement_cost": "25.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':20 'amus':21 'bang':1 'cat':11 'drama':5 'epic':4 'face':14 'kwai':2 'madman':8 'must':13 'park':22 'shark':17"
	},
	{
		"film_id": 54,
		"title": "BANGER PINOCCHIO",
		"description": "A Awe-Inspiring Drama of a Car And a Pastry Chef who must Chase a Crocodile in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "0.99",
		"length": 113,
		"replacement_cost": "15.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'awe':5 'awe-inspir':4 'banger':1 'car':10 'chase':17 'chef':14 'crocodil':19 'drama':7 'first':22 'inspir':6 'man':23 'must':16 'pastri':13 'pinocchio':2 'space':24 'station':25"
	},
	{
		"film_id": 55,
		"title": "BARBARELLA STREETCAR",
		"description": "A Awe-Inspiring Story of a Feminist And a Cat who must Conquer a Dog in A Monastery",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 65,
		"replacement_cost": "27.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Behind the Scenes\"]",
		"fulltext": "'awe':5 'awe-inspir':4 'barbarella':1 'cat':13 'conquer':16 'dog':18 'feminist':10 'inspir':6 'monasteri':21 'must':15 'stori':7 'streetcar':2"
	},
	{
		"film_id": 56,
		"title": "BAREFOOT MANCHURIAN",
		"description": "A Intrepid Story of a Cat And a Student who must Vanquish a Girl in An Abandoned Amusement Park",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 129,
		"replacement_cost": "15.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'abandon':19 'amus':20 'barefoot':1 'cat':8 'girl':16 'intrepid':4 'manchurian':2 'must':13 'park':21 'stori':5 'student':11 'vanquish':14"
	},
	{
		"film_id": 57,
		"title": "BASIC EASY",
		"description": "A Stunning Epistle of a Man And a Husband who must Reach a Mad Scientist in A Jet Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "2.99",
		"length": 90,
		"replacement_cost": "18.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\"]",
		"fulltext": "'basic':1 'boat':21 'easi':2 'epistl':5 'husband':11 'jet':20 'mad':16 'man':8 'must':13 'reach':14 'scientist':17 'stun':4"
	},
	{
		"film_id": 58,
		"title": "BEACH HEARTBREAKERS",
		"description": "A Fateful Display of a Womanizer And a Mad Scientist who must Outgun a A Shark in Soviet Georgia",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 122,
		"replacement_cost": "16.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'beach':1 'display':5 'fate':4 'georgia':21 'heartbreak':2 'mad':11 'must':14 'outgun':15 'scientist':12 'shark':18 'soviet':20 'woman':8"
	},
	{
		"film_id": 59,
		"title": "BEAR GRACELAND",
		"description": "A Astounding Saga of a Dog And a Boy who must Kill a Teacher in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "2.99",
		"length": 160,
		"replacement_cost": "20.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\"]",
		"fulltext": "'astound':4 'bear':1 'boy':11 'dog':8 'first':19 'graceland':2 'kill':14 'man':20 'must':13 'saga':5 'space':21 'station':22 'teacher':16"
	},
	{
		"film_id": 60,
		"title": "BEAST HUNCHBACK",
		"description": "A Awe-Inspiring Epistle of a Student And a Squirrel who must Defeat a Boy in Ancient China",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "4.99",
		"length": 89,
		"replacement_cost": "22.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'ancient':20 'awe':5 'awe-inspir':4 'beast':1 'boy':18 'china':21 'defeat':16 'epistl':7 'hunchback':2 'inspir':6 'must':15 'squirrel':13 'student':10"
	},
	{
		"film_id": 61,
		"title": "BEAUTY GREASE",
		"description": "A Fast-Paced Display of a Composer And a Moose who must Sink a Robot in An Abandoned Mine Shaft",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 175,
		"replacement_cost": "28.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'abandon':21 'beauti':1 'compos':10 'display':7 'fast':5 'fast-pac':4 'greas':2 'mine':22 'moos':13 'must':15 'pace':6 'robot':18 'shaft':23 'sink':16"
	},
	{
		"film_id": 62,
		"title": "BED HIGHBALL",
		"description": "A Astounding Panorama of a Lumberjack And a Dog who must Redeem a Woman in An Abandoned Fun House",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 106,
		"replacement_cost": "23.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'abandon':19 'astound':4 'bed':1 'dog':11 'fun':20 'highbal':2 'hous':21 'lumberjack':8 'must':13 'panorama':5 'redeem':14 'woman':16"
	},
	{
		"film_id": 63,
		"title": "BEDAZZLED MARRIED",
		"description": "A Astounding Character Study of a Madman And a Robot who must Meet a Mad Scientist in An Abandoned Fun House",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 73,
		"replacement_cost": "21.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':21 'astound':4 'bedazzl':1 'charact':5 'fun':22 'hous':23 'mad':17 'madman':9 'marri':2 'meet':15 'must':14 'robot':12 'scientist':18 'studi':6"
	},
	{
		"film_id": 64,
		"title": "BEETHOVEN EXORCIST",
		"description": "A Epic Display of a Pioneer And a Student who must Challenge a Butler in The Gulf of Mexico",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 151,
		"replacement_cost": "26.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'beethoven':1 'butler':16 'challeng':14 'display':5 'epic':4 'exorcist':2 'gulf':19 'mexico':21 'must':13 'pioneer':8 'student':11"
	},
	{
		"film_id": 65,
		"title": "BEHAVIOR RUNAWAY",
		"description": "A Unbelieveable Drama of a Student And a Husband who must Outrace a Sumo Wrestler in Berlin",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "4.99",
		"length": 100,
		"replacement_cost": "20.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'behavior':1 'berlin':19 'drama':5 'husband':11 'must':13 'outrac':14 'runaway':2 'student':8 'sumo':16 'unbeliev':4 'wrestler':17"
	},
	{
		"film_id": 66,
		"title": "BENEATH RUSH",
		"description": "A Astounding Panorama of a Man And a Monkey who must Discover a Man in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "0.99",
		"length": 53,
		"replacement_cost": "27.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'astound':4 'beneath':1 'discov':14 'first':19 'man':8,16,20 'monkey':11 'must':13 'panorama':5 'rush':2 'space':21 'station':22"
	},
	{
		"film_id": 67,
		"title": "BERETS AGENT",
		"description": "A Taut Saga of a Crocodile And a Boy who must Overcome a Technical Writer in Ancient China",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 77,
		"replacement_cost": "24.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\"]",
		"fulltext": "'agent':2 'ancient':19 'beret':1 'boy':11 'china':20 'crocodil':8 'must':13 'overcom':14 'saga':5 'taut':4 'technic':16 'writer':17"
	},
	{
		"film_id": 68,
		"title": "BETRAYED REAR",
		"description": "A Emotional Character Study of a Boat And a Pioneer who must Find a Explorer in A Shark Tank",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 122,
		"replacement_cost": "26.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'betray':1 'boat':9 'charact':5 'emot':4 'explor':17 'find':15 'must':14 'pioneer':12 'rear':2 'shark':20 'studi':6 'tank':21"
	},
	{
		"film_id": 69,
		"title": "BEVERLY OUTLAW",
		"description": "A Fanciful Documentary of a Womanizer And a Boat who must Defeat a Madman in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "2.99",
		"length": 85,
		"replacement_cost": "21.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'bever':1 'boat':11 'defeat':14 'documentari':5 'fanci':4 'first':19 'madman':16 'man':20 'must':13 'outlaw':2 'space':21 'station':22 'woman':8"
	},
	{
		"film_id": 70,
		"title": "BIKINI BORROWERS",
		"description": "A Astounding Drama of a Astronaut And a Cat who must Discover a Woman in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "4.99",
		"length": 142,
		"replacement_cost": "26.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'astound':4 'astronaut':8 'bikini':1 'borrow':2 'cat':11 'discov':14 'drama':5 'first':19 'man':20 'must':13 'space':21 'station':22 'woman':16"
	},
	{
		"film_id": 71,
		"title": "BILKO ANONYMOUS",
		"description": "A Emotional Reflection of a Teacher And a Man who must Meet a Cat in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "4.99",
		"length": 100,
		"replacement_cost": "25.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'anonym':2 'bilko':1 'cat':16 'emot':4 'first':19 'man':11,20 'meet':14 'must':13 'reflect':5 'space':21 'station':22 'teacher':8"
	},
	{
		"film_id": 72,
		"title": "BILL OTHERS",
		"description": "A Stunning Saga of a Mad Scientist And a Forensic Psychologist who must Challenge a Squirrel in A MySQL Convention",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "2.99",
		"length": 93,
		"replacement_cost": "12.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'bill':1 'challeng':16 'convent':22 'forens':12 'mad':8 'must':15 'mysql':21 'other':2 'psychologist':13 'saga':5 'scientist':9 'squirrel':18 'stun':4"
	},
	{
		"film_id": 73,
		"title": "BINGO TALENTED",
		"description": "A Touching Tale of a Girl And a Crocodile who must Discover a Waitress in Nigeria",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 150,
		"replacement_cost": "22.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'bingo':1 'crocodil':11 'discov':14 'girl':8 'must':13 'nigeria':18 'tale':5 'talent':2 'touch':4 'waitress':16"
	},
	{
		"film_id": 74,
		"title": "BIRCH ANTITRUST",
		"description": "A Fanciful Panorama of a Husband And a Pioneer who must Outgun a Dog in A Baloon",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "4.99",
		"length": 162,
		"replacement_cost": "18.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'antitrust':2 'baloon':19 'birch':1 'dog':16 'fanci':4 'husband':8 'must':13 'outgun':14 'panorama':5 'pioneer':11"
	},
	{
		"film_id": 75,
		"title": "BIRD INDEPENDENCE",
		"description": "A Thrilling Documentary of a Car And a Student who must Sink a Hunter in The Canadian Rockies",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "4.99",
		"length": 163,
		"replacement_cost": "14.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'bird':1 'canadian':19 'car':8 'documentari':5 'hunter':16 'independ':2 'must':13 'rocki':20 'sink':14 'student':11 'thrill':4"
	},
	{
		"film_id": 76,
		"title": "BIRDCAGE CASPER",
		"description": "A Fast-Paced Saga of a Frisbee And a Astronaut who must Overcome a Feminist in Ancient India",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "0.99",
		"length": 103,
		"replacement_cost": "23.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'ancient':20 'astronaut':13 'birdcag':1 'casper':2 'fast':5 'fast-pac':4 'feminist':18 'frisbe':10 'india':21 'must':15 'overcom':16 'pace':6 'saga':7"
	},
	{
		"film_id": 77,
		"title": "BIRDS PERDITION",
		"description": "A Boring Story of a Womanizer And a Pioneer who must Face a Dog in California",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 61,
		"replacement_cost": "15.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'bird':1 'bore':4 'california':18 'dog':16 'face':14 'must':13 'perdit':2 'pioneer':11 'stori':5 'woman':8"
	},
	{
		"film_id": 78,
		"title": "BLACKOUT PRIVATE",
		"description": "A Intrepid Yarn of a Pastry Chef And a Mad Scientist who must Challenge a Secret Agent in Ancient Japan",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "2.99",
		"length": 85,
		"replacement_cost": "12.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'agent':19 'ancient':21 'blackout':1 'challeng':16 'chef':9 'intrepid':4 'japan':22 'mad':12 'must':15 'pastri':8 'privat':2 'scientist':13 'secret':18 'yarn':5"
	},
	{
		"film_id": 79,
		"title": "BLADE POLISH",
		"description": "A Thoughtful Character Study of a Frisbee And a Pastry Chef who must Fight a Dentist in The First Manned Space Station",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "0.99",
		"length": 114,
		"replacement_cost": "10.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'blade':1 'charact':5 'chef':13 'dentist':18 'fight':16 'first':21 'frisbe':9 'man':22 'must':15 'pastri':12 'polish':2 'space':23 'station':24 'studi':6 'thought':4"
	},
	{
		"film_id": 80,
		"title": "BLANKET BEVERLY",
		"description": "A Emotional Documentary of a Student And a Girl who must Build a Boat in Nigeria",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "2.99",
		"length": 148,
		"replacement_cost": "21.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'bever':2 'blanket':1 'boat':16 'build':14 'documentari':5 'emot':4 'girl':11 'must':13 'nigeria':18 'student':8"
	},
	{
		"film_id": 81,
		"title": "BLINDNESS GUN",
		"description": "A Touching Drama of a Robot And a Dentist who must Meet a Hunter in A Jet Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "4.99",
		"length": 103,
		"replacement_cost": "29.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Behind the Scenes\"]",
		"fulltext": "'blind':1 'boat':20 'dentist':11 'drama':5 'gun':2 'hunter':16 'jet':19 'meet':14 'must':13 'robot':8 'touch':4"
	},
	{
		"film_id": 82,
		"title": "BLOOD ARGONAUTS",
		"description": "A Boring Drama of a Explorer And a Man who must Kill a Lumberjack in A Manhattan Penthouse",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "0.99",
		"length": 71,
		"replacement_cost": "13.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'argonaut':2 'blood':1 'bore':4 'drama':5 'explor':8 'kill':14 'lumberjack':16 'man':11 'manhattan':19 'must':13 'penthous':20"
	},
	{
		"film_id": 83,
		"title": "BLUES INSTINCT",
		"description": "A Insightful Documentary of a Boat And a Composer who must Meet a Forensic Psychologist in An Abandoned Fun House",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "2.99",
		"length": 50,
		"replacement_cost": "18.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':20 'blue':1 'boat':8 'compos':11 'documentari':5 'forens':16 'fun':21 'hous':22 'insight':4 'instinct':2 'meet':14 'must':13 'psychologist':17"
	},
	{
		"film_id": 84,
		"title": "BOILED DARES",
		"description": "A Awe-Inspiring Story of a Waitress And a Dog who must Discover a Dentist in Ancient Japan",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "4.99",
		"length": 102,
		"replacement_cost": "13.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'ancient':20 'awe':5 'awe-inspir':4 'boil':1 'dare':2 'dentist':18 'discov':16 'dog':13 'inspir':6 'japan':21 'must':15 'stori':7 'waitress':10"
	},
	{
		"film_id": 85,
		"title": "BONNIE HOLOCAUST",
		"description": "A Fast-Paced Story of a Crocodile And a Robot who must Find a Moose in Ancient Japan",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "0.99",
		"length": 63,
		"replacement_cost": "29.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Deleted Scenes\"]",
		"fulltext": "'ancient':20 'bonni':1 'crocodil':10 'fast':5 'fast-pac':4 'find':16 'holocaust':2 'japan':21 'moos':18 'must':15 'pace':6 'robot':13 'stori':7"
	},
	{
		"film_id": 86,
		"title": "BOOGIE AMELIE",
		"description": "A Lacklusture Character Study of a Husband And a Sumo Wrestler who must Succumb a Technical Writer in The Gulf of Mexico",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 6,
		"rental_rate": "4.99",
		"length": 121,
		"replacement_cost": "11.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'ameli':2 'boogi':1 'charact':5 'gulf':22 'husband':9 'lacklustur':4 'mexico':24 'must':15 'studi':6 'succumb':16 'sumo':12 'technic':18 'wrestler':13 'writer':19"
	},
	{
		"film_id": 87,
		"title": "BOONDOCK BALLROOM",
		"description": "A Fateful Panorama of a Crocodile And a Boy who must Defeat a Monkey in The Gulf of Mexico",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "0.99",
		"length": 76,
		"replacement_cost": "14.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Behind the Scenes\"]",
		"fulltext": "'ballroom':2 'boondock':1 'boy':11 'crocodil':8 'defeat':14 'fate':4 'gulf':19 'mexico':21 'monkey':16 'must':13 'panorama':5"
	},
	{
		"film_id": 88,
		"title": "BORN SPINAL",
		"description": "A Touching Epistle of a Frisbee And a Husband who must Pursue a Student in Nigeria",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "4.99",
		"length": 179,
		"replacement_cost": "17.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'born':1 'epistl':5 'frisbe':8 'husband':11 'must':13 'nigeria':18 'pursu':14 'spinal':2 'student':16 'touch':4"
	},
	{
		"film_id": 89,
		"title": "BORROWERS BEDAZZLED",
		"description": "A Brilliant Epistle of a Teacher And a Sumo Wrestler who must Defeat a Man in An Abandoned Fun House",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "0.99",
		"length": 63,
		"replacement_cost": "22.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\",\"Deleted Scenes\",\"Behind the Scenes\"]",
		"fulltext": "'abandon':20 'bedazzl':2 'borrow':1 'brilliant':4 'defeat':15 'epistl':5 'fun':21 'hous':22 'man':17 'must':14 'sumo':11 'teacher':8 'wrestler':12"
	},
	{
		"film_id": 90,
		"title": "BOULEVARD MOB",
		"description": "A Fateful Epistle of a Moose And a Monkey who must Confront a Lumberjack in Ancient China",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 3,
		"rental_rate": "0.99",
		"length": 63,
		"replacement_cost": "11.99",
		"rating": "R",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'ancient':18 'boulevard':1 'china':19 'confront':14 'epistl':5 'fate':4 'lumberjack':16 'mob':2 'monkey':11 'moos':8 'must':13"
	},
	{
		"film_id": 182,
		"title": "CONTROL ANTHEM",
		"description": "A Fateful Documentary of a Robot And a Student who must Battle a Cat in A Monastery",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "4.99",
		"length": 185,
		"replacement_cost": "9.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Commentaries\"]",
		"fulltext": "'anthem':2 'battl':14 'cat':16 'control':1 'documentari':5 'fate':4 'monasteri':19 'must':13 'robot':8 'student':11"
	},
	{
		"film_id": 91,
		"title": "BOUND CHEAPER",
		"description": "A Thrilling Panorama of a Database Administrator And a Astronaut who must Challenge a Lumberjack in A Baloon",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "0.99",
		"length": 98,
		"replacement_cost": "17.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Behind the Scenes\"]",
		"fulltext": "'administr':9 'astronaut':12 'baloon':20 'bound':1 'challeng':15 'cheaper':2 'databas':8 'lumberjack':17 'must':14 'panorama':5 'thrill':4"
	},
	{
		"film_id": 92,
		"title": "BOWFINGER GABLES",
		"description": "A Fast-Paced Yarn of a Waitress And a Composer who must Outgun a Dentist in California",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "4.99",
		"length": 72,
		"replacement_cost": "19.99",
		"rating": "NC-17",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'bowfing':1 'california':20 'compos':13 'dentist':18 'fast':5 'fast-pac':4 'gabl':2 'must':15 'outgun':16 'pace':6 'waitress':10 'yarn':7"
	},
	{
		"film_id": 93,
		"title": "BRANNIGAN SUNRISE",
		"description": "A Amazing Epistle of a Moose And a Crocodile who must Outrace a Dog in Berlin",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "4.99",
		"length": 121,
		"replacement_cost": "27.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'amaz':4 'berlin':18 'brannigan':1 'crocodil':11 'dog':16 'epistl':5 'moos':8 'must':13 'outrac':14 'sunris':2"
	},
	{
		"film_id": 94,
		"title": "BRAVEHEART HUMAN",
		"description": "A Insightful Story of a Dog And a Pastry Chef who must Battle a Girl in Berlin",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "2.99",
		"length": 176,
		"replacement_cost": "14.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Deleted Scenes\"]",
		"fulltext": "'battl':15 'berlin':19 'braveheart':1 'chef':12 'dog':8 'girl':17 'human':2 'insight':4 'must':14 'pastri':11 'stori':5"
	},
	{
		"film_id": 95,
		"title": "BREAKFAST GOLDFINGER",
		"description": "A Beautiful Reflection of a Student And a Student who must Fight a Moose in Berlin",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 5,
		"rental_rate": "4.99",
		"length": 123,
		"replacement_cost": "18.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Deleted Scenes\"]",
		"fulltext": "'beauti':4 'berlin':18 'breakfast':1 'fight':14 'goldfing':2 'moos':16 'must':13 'reflect':5 'student':8,11"
	},
	{
		"film_id": 96,
		"title": "BREAKING HOME",
		"description": "A Beautiful Display of a Secret Agent And a Monkey who must Battle a Sumo Wrestler in An Abandoned Mine Shaft",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "2.99",
		"length": 169,
		"replacement_cost": "21.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\"]",
		"fulltext": "'abandon':21 'agent':9 'battl':15 'beauti':4 'break':1 'display':5 'home':2 'mine':22 'monkey':12 'must':14 'secret':8 'shaft':23 'sumo':17 'wrestler':18"
	},
	{
		"film_id": 97,
		"title": "BRIDE INTRIGUE",
		"description": "A Epic Tale of a Robot And a Monkey who must Vanquish a Man in New Orleans",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "0.99",
		"length": 56,
		"replacement_cost": "24.99",
		"rating": "G",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\",\"Commentaries\",\"Behind the Scenes\"]",
		"fulltext": "'bride':1 'epic':4 'intrigu':2 'man':16 'monkey':11 'must':13 'new':18 'orlean':19 'robot':8 'tale':5 'vanquish':14"
	},
	{
		"film_id": 98,
		"title": "BRIGHT ENCOUNTERS",
		"description": "A Fateful Yarn of a Lumberjack And a Feminist who must Conquer a Student in A Jet Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 4,
		"rental_rate": "4.99",
		"length": 73,
		"replacement_cost": "12.99",
		"rating": "PG-13",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'boat':20 'bright':1 'conquer':14 'encount':2 'fate':4 'feminist':11 'jet':19 'lumberjack':8 'must':13 'student':16 'yarn':5"
	},
	{
		"film_id": 99,
		"title": "BRINGING HYSTERICAL",
		"description": "A Fateful Saga of a A Shark And a Technical Writer who must Find a Woman in A Jet Boat",
		"release_year": 2006,
		"language_id": 1,
		"original_language_id": null,
		"rental_duration": 7,
		"rental_rate": "2.99",
		"length": 136,
		"replacement_cost": "14.99",
		"rating": "PG",
		"last_update": "2006-02-15 05:03:42",
		"special_features": "[\"Trailers\"]",
		"fulltext": "'boat':22 'bring':1 'fate':4 'find':16 'hyster':2 'jet':21 'must':15 'saga':5 'shark':9 'technic':12 'woman':18 'writer':13"
	}
]
